# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 00:24
from __future__ import unicode_literals

import ccposts.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('body', models.TextField(blank=True, verbose_name=b'\xe6\xad\xa3\xe6\x96\x87')),
                ('abstract', models.CharField(blank=True, help_text=b'If possible, use the first 200 words.', max_length=200, verbose_name=b'\xe6\x91\x98\xe8\xa6\x81')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe4\xb8\x8a\xe6\xac\xa1\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('status', models.CharField(choices=[(b'd', b'Draft'), (b'p', b'Published')], max_length=1, verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe7\x8a\xb6\xe6\x80\x81')),
                ('slug', models.SlugField(unique=True)),
                ('commentcount', models.PositiveIntegerField(blank=True, default=0, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba')),
                ('views', models.PositiveIntegerField(blank=True, default=0, verbose_name=b'\xe6\xb5\x8f\xe8\xa7\x88\xe9\x87\x8f')),
                ('likes', models.PositiveIntegerField(blank=True, default=0, verbose_name=b'\xe7\x82\xb9\xe8\xb5\x9e\xe6\x95\xb0')),
                ('topped', models.NullBooleanField(default=True, verbose_name=b'\xe7\xbd\xae\xe9\xa1\xb6')),
                ('html_file', models.FileField(blank=True, upload_to=ccposts.models.get_html_name, verbose_name=b'\xe4\xb8\x8a\xe4\xbc\xa0html\xe6\x96\x87\xe4\xbb\xb6')),
                ('md_file', models.FileField(blank=True, upload_to=ccposts.models.get_upload_md_name, verbose_name=b'\xe4\xb8\x8a\xe4\xbc\xa0md\xe6\x96\x87\xe4\xbb\xb6')),
            ],
            options={
                'ordering': ['-last_modified_time'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ccposts.models.get_upload_img_name)),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe4\xb8\x8a\xe4\xbc\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ccposts.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=30, verbose_name=b'\xe7\x9b\xae\xe5\xbd\x95\xe5\x90\x8d\xe7\xa7\xb0')),
                ('articlecount', models.IntegerField(default=0, verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe7\xaf\x87\xe6\x95\xb0')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=30, verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe\xe5\x90\x8d')),
                ('articlecount', models.IntegerField(default=0, verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe\xe4\xb8\x8b\xe6\x96\x87\xe7\xab\xa0\xe6\x95\xb0')),
            ],
            options={
                'ordering': ['tagname'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccposts.Category', verbose_name=b'\xe7\x9b\xae\xe5\xbd\x95'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ccposts.Tag', verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe'),
        ),
    ]
